[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MathTeXEngine = "0a4f8689-d25c-4efe-a92b-7142dfc1aa53"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
UnROOT = "3cd96dde-e98d-4713-81e9-a4a1b0235ce9"
